### ISSUE TITLE
coordinates rearragement

### ISSUE THREAD

**Issue by pauplaterra** [crest-lab/crest#106]
Hello,

I wonder why the .xyz input file is rearranged by CREST. Is there any file/option to obtain the initial structure but with the atoms in the order given by tautomers.xyz as an example? or any option to avoid rearrangement?

Thank you!

**Comment by pprcht** [comment]
In the conformational sampling workflows the atom reordering is turned off by default. 

For the protonation site and tautomer screening the files have to be sorted as there is a change in the total number of atoms in between the steps and because the hydrogen atoms are permuted by the procedure. The order of the heavy atoms technically stays the same.

Currently there is no option for tracking the permutations and restoring the original order. If your trying to run e.g. a RMSD on the structures you could only use the non-hydrogen atoms for that since they are the same order for all protomers/tautomers.
