### ISSUE TITLE
RAM Usage during Structure Crossing

### ISSUE THREAD

**Issue by jFlorm** [crest-lab/crest#109]
Hello,

I am trying to use crest for a conformational search on larger organic molecules (up to 85 atoms) on a cluster system. The meta dynamics and the optimization of the rotamers are running fine, but the calculation always breaks during the structural crossing (see end of crest.log). The clustersystem then gives the error "forrtl: severe (41): insufficient virtual memory" (see synPh_Start_Crest.e8535977), even though there were up to 250GB of RAM available. Is this a problem with the RAM acquisition of crest or is there really more RAM needed? If this is the case, could you give an approximation, how much RAM is needed for the structural crossing of molecules with this size?

I attached the complete folder with the output files (except for the large rotamer-files) as a zip archive, where synPh_Start_Crest.xyz is the starting structure, synPh_Start_Crest.job is used to start the calculation via the batch system on our cluster, synPh_Start_Crest.e8535977 is the output of the batch system after the calculation stopped and crest.log is the output of the crest calculation.
[RAM_Usage_Problem_without_rotamers.zip](https://github.com/grimme-lab/crest/files/8402450/RAM_Usage_Problem_without_rotamers.zip)

Thank you very much for your help!

**Comment by jFlorm** [comment]
Hi,
thank you very much for the quick answer. I have now run the code with version 2.11.2 (the compiled crest.zip from the release page) but the calculation still did not finish normally. The insufficient virtual memory error reoccurres, although from the 64 GB of available RAM, crest uses only 660 MB (mem) and requested roughly 4,5GB of virtual memory (vmem). I have attached the output. I am using xtb version 6.4.1, could that be the problem?
[Output_Crest_2-11-2.zip](https://github.com/grimme-lab/crest/files/8415684/Output_Crest_2-11-2.zip)

**Comment by pprcht** [comment]
xtb 6.4.1 should be fine.

The error does seem to occur at another point now, but I can't reproduce it for myself and neither have I seen it for another system before. I have to admit that its cause currently eludes me.

Can you rule out that the error is caused by your systems architecture or the parallelization? vmem usage could be an indication that the error lies with the latter.

**Comment by jFlorm** [comment]
Ok I have started the calculation again with one single processor, perhaps this will work. We have tried to run this job on two independent architectures, but on both the jobs terminated during the structural crossing, so i would hope that there is no lager error with the architecture. 
Did the calculation terminate normally on your system?

**Comment by pprcht** [comment]
Upon further inspection, I think I have found something in the crossing code.
Turns out that there are some stupidly large temporary arrays the program tries to allocate in the GC step if the molecule has a really large number of  degenerate (or at least energetically close) minima.
Your system has a large number of methyl groups, so it fell into that category.

I don't know yet how to avoid this consistently, but i will look into it. 
For your specific case try to turn the entire GC step off (`--nocross`). The structures generated here will anyways most likely be non-sense since the GC will just permute the all those degenerate minima. The minima found up to the GC step will be sufficient, and you won't even need to recalculate everything. Just take the last `crest_rotamers_X.xyz` file (`X` = the highest number, usually) and reoptimize it with `crest -screen crest_rotamers_X.xyz` (and  `--alpb ether`, in your case I think)

**Comment by jFlorm** [comment]
Thank you very much for looking into the issue. I have already run the calculations with --nocross and they terminated successfully and I am now working with these structures. 
While using the newer crest version 2.11.2, I have noticed that it stops writing output to the terminal during the first meta dynamics, although the optimizations are still running. Is this normal?
