### ISSUE TITLE
"forrtl: warning (768): Internal file write-to-self; undefined results" for Crest 2.12

### ISSUE THREAD

**Issue by lizhiq16** [crest-lab/crest#121]
```
------------------------------------------------
Generating MTD length from a flexibility measure
------------------------------------------------
forrtl: warning (768): Internal file write-to-self; undefined results
 Calculating WBOs... done.
forrtl: warning (768): Internal file write-to-self; undefined results
 Calculating NCI flexibility... done.
     covalent flexibility measure :   0.005
 non-covalent flexibility measure :   0.816
 flexibility measure :   0.030
 t(MTD) / ps    :     2.5
 Σ(t(MTD)) / ps :    15.0 (6 MTDs)
```
 
The search process seems went smoothly, but why this  warning (768) was given  (xtb-6.5.0+crest-2.12)?
And it seems that crest-2.11.2 is not compatible with xtb-6.5.0. When used this combination, the optimization use gfn0 but not gfn2 as default?

**Comment by pprcht** [comment]
I don't quite know where the forrtl warning is coming from, but I have noticed them myself. They do not seem to appear for all systems, which is a bit strange.
And yes, the search process seems unaffected.

The defaults were not changed for xtb 6.5.0, it should work the same as before. But I will look into that again.

**Comment by lizhiq16** [comment]
the molecule I used was benzaldehyde, you may try to reproduce it.

**Comment by pprcht** [comment]
#122 should fix the `forrtl` message. Although I'm not sure why it happened in the first place.

As for the xtb-6.5.0 dependence, I have checked both crest 2.12 and crest 2.11.2 again with several molecules, but found nothing out of the ordinary (besides this `forrtl` stuff). Did you look at the flexibility measure calculation when you checked this? Because this is *always* done with an GFN0 and a GFN-FF singplepoint in order to be consistent.
