### ISSUE TITLE
Memory allocation problem during CREST run with substructure fixing

### ISSUE THREAD

**Issue by uhrzeitranger** [crest-lab/crest#187]
Dear all,

I repeatedly run into what seems like a memory allocation problem during my CREST runs, when I fix parts of my input structure. The meta-MD iterations run smoothly. The program runs additional regular MDs on the lowest 4 conformers, which also finish smoothly and the structures found are appended to a file called `crest_rotamers_2.xyz`. Reproducibly, the error occurs at the end of optimizing the structures in this file with tight thresholds. I run the calculations on 64 threads and an attempt to allocate more memory did not fix the problem.

The error message reads either:
`***Error in crest: double free or corruption (!prev): 0x000055e2edce4700 ***`
or:
`*** Error in crest: free(): invalid next size (normal): 0x000055fadcd523c0 ***`

I attached the full output files documenting the problem.

More details on what I am attempting to do: I am trying to do CRE sampling on a functionalized polyproline peptide that has a PPII-helical conformation (experimentally). Hence, after optimizing the input structure, which is coming from a crystal stucture, at GFN2-xTB level of theory, I attempted to constrain the PPII helix using the constraints.inp file attached.

I appreciate any thoughts on what might be the origin of this problem.

Cheers,

Linus
[Memory_allocation_problem_files.zip](https://github.com/crest-lab/crest/files/11109554/Memory_allocation_problem_files.zip)

**Comment by pprcht** [comment]
Hi,
It could be possible you are running into memory issues due to the parallelization. I can see you are using `-T 64`, which I assume is the number of threads available on one of your cluster nodes. There have definitely been issues in the past where there are several CPUs on a single node and the communication between them during the parallelization broke down.

However, the error message suggests that the program tries to access data from memory where should be none, i.e., the n+1 element of an array with only n entries. You can see that this seems to be true as the error occurs right after the last optimization in the loop. That's weird because all other optimization loops worked to that point, and they use the same routine. 

My guess is that it really has something to to with the parallelization, could you try if the error still occurs with fewer threads? E.g. `-T 16` or `-T 32`? How to prevent it in-code is another story...

**Comment by uhrzeitranger** [comment]
Hey,
I tried running calculations with `-T 32`, `-T 16` and `-T 8` but the runs still break down at the end of this optimization loop. I attached the log files containing the error messages again. I did not run into any errors when doing CREST on this cluster with substructure fixing on a smaller molecule previously, so I don't think this problem generally occurs when trying to parallelize on this cluster. I will try to further investigate if my input structure / constraining are somehow problematic.
[Parallelization_8-32.zip](https://github.com/crest-lab/crest/files/11147939/Parallelization_8-32.zip)
