### ISSUE TITLE
Spherical cavity radius

### ISSUE THREAD

**Issue by matteo-northvolt** [crest-lab/crest#188]
Good morning,

I may be mistaken, but I think that in the _rcontrol_ file what is defined as 'Spherical cavity radius' is actually a diameter.

**Comment by pprcht** [comment]
Hello,
I'm pretty sure it is a radius. The value is in Bohr, so if you are wondering about the magnitude, that is probably the reason.

**Comment by matteo-northvolt** [comment]
Hey pprcht, thanks for your answer!

I just uploaded two files
1. My geometry, it is a solvent sphere of 7 A radius obtained with packmol: [20ec_r7.txt](https://github.com/crest-lab/crest/files/11120823/20ec_r7.txt)
2. The output of rcontrol initialization: [dens1.2.txt](https://github.com/crest-lab/crest/files/11120820/dens1.2.txt)

As you can see I set the density (from input) equal to the one detected by xtb (1.20 g/cm³) that gives:
`Spherical cavity radius :    25.431 Bohr`
So I assume the radius of the potential wall is 13.46 A that is exactly twice the radius of the spherical geometry I am using.

**Comment by pprcht** [comment]
Oh you mean specifically in the nanoreactor setup? Okay I will have to check. In the end xtb reads the value from rcontrol as a radius.

I mean to remember, however, that one must not set the wall potential radius equal to the size of the cluster at unmodified input density and this factor of two  may be intentional for the nanoreactor. The molecules will feel the potential quite rapidly otherwise, i.e., at unmodified input density there should be no compression. Back when this was coded it followed the original setup described in the paper, of that I'm certain.
