### ISSUE TITLE
CREST crashes when a large number of conformers are generated

### ISSUE THREAD

**Issue by chemistza** [crest-lab/crest#20]
I'm finding that CREST crashes wth some jobs that generate a large number of conformers. In particular, I have attached the .xyz file of a Fe-triphos organometallic compound. The last few lines of the log file are usually:

```
Starting Meta-MD  12 with the settings:
     MD time /ps        :   135.0
     dt /fs             :     2.0
     dumpstep(trj) /fs  :     100
     dumpstep(Vbias)/ps :     1.0
     Vbias prefactor(k) :  0.1410
     Vbias exponent(α)  :    0.28
*Meta-MD 13 finished*
*Meta-MD 11 finished*
*Meta-MD 14 finished*
*Meta-MD 7 finished*
*Meta-MD 5 finished*
*Meta-MD 8 finished*
*Meta-MD 12 finished*
*Meta-MD 1 finished*
*Meta-MD 10 finished*
*Meta-MD 2 finished*
*Meta-MD 9 finished*
*Meta-MD 3 finished*
*Meta-MD 6 finished*
*Meta-MD 4 finished*
 
-----------------------
Multilevel Optimization
-----------------------
 
 -------------------------
 1. crude pre-optimization
 -------------------------
```

The error message obtained is:

`error while reading coord line`

The version of CREST is 2.10.2, and XTB is 6.3.3. My job run-script is as follows:
```
export MKL_NUM_THREADS=28
export OMP_THREAD_LIMIT=28
export OMP_NUM_THREADS=${OMP_THREAD_LIMIT},1
export OMP_STACKSIZE=2G
ulimit -s unlimited

crest coords.xyz -gfnff > crest.log
```

The above calculation was run with gfnff, but this error typically also occurs with gfn1 and gfn2
[coords.zip](https://github.com/grimme-lab/crest/files/5559047/coords.zip)

**Comment by pprcht** [comment]
Yes, this was an older issue that we came across in the past  several times also. I can't clearly remember if it really was the number of conformers that is the problem here, though.
Try the current [development version](https://github.com/grimme-lab/crest/releases/tag/2.11-dev), there it should work. 
With this version I already had ensembles with close to a million conformers, so in that regard it should be save. If it still crashes at a similar position it could be some other molecule specific problem.

I occasionally update the development binary, but we will also do the regular release until the end of the year, I hope.

**Comment by chemistza** [comment]
Thanks for the reply. Unfortunately I can't run the development version of CREST as the kernel on the cluster I use is too old. Would it be possible to compile an "old kernel" version like for the previous releases?

**Comment by pprcht** [comment]
Yeah, sure, I updated it.

**Comment by chemistza** [comment]
Great, thanks!
