### ISSUE TITLE
Returning dipole moment components for conformers?

### ISSUE THREAD

**Issue by nseifert** [crest-lab/crest#204]
Hi,

This is less an issue and more of a technical question,  but is there a way to have CREST write, or output, the xtb dipole moment components for each of the final set of energy-sorted conformers in a typical conformational search? 

This would be extremely helpful for spectroscopy applications when calculating conformational ensembles. I have been running my conformers back via xtb or a quick B3LYP single-point calculation to get the dipoles, but I'm guessing this is overkill.

**Comment by pprcht** [comment]
Hello,

At the moment such information is not kept from the calculations, but I can see what I can do. Shouldn't be too difficult.

**Comment by pprcht** [comment]
I added a flag to the development version.
You can either just add `-prop dipole` to your calculation, or if you already have an ensemble do something like
```bash
crest -for crest_conformers.xyz -prop dipole
```
both will write a file `crest.dipole` that contains x, y, and z components and the total dipole moment in Debye for each structure (one per line).

And since the development version is not build into the continuous release, here is also a binary:
[crest.zip](https://github.com/crest-lab/crest/files/11779182/crest.zip)
