### ISSUE TITLE
Unites of "kpush" and "alp" parameters

### ISSUE THREAD

**Issue by moabe84** [crest-lab/crest#218]
Hi Philipp,
I'd like to know the unites of the "kpush" and "alp" parameters in the $metadyn block. Are they mHartree (kpush) and Bohr^-1 (alp)? Many thanks.

Mostafa

**Comment by pprcht** [comment]
k is in Hartree, but depending on the printout you are referring to it might be given *per atom* (hence the seemingly small number). Think about it as: larger systems need overall more energy to change conformation

alpha is in Bohr<sup> -2</sup> since the RMSD as collective variable is squared in the metadynamics potential.

**Comment by moabe84** [comment]
Thanks. It's very helpful.
