### ISSUE TITLE
CREST somewhat ignores param_gfn1-xtb?

### ISSUE THREAD

**Issue by yk07212** [crest-lab/crest#223]
Hi, 
I am trying to run CREST using some different parameters for GFN1. However, the structures and energies it gives are based on the original parameters? 
The odd thing is that it seems to load the custom parameters for the initial structure optimization as I get the "Initial geometry optimization failed!" error if I set the parameters to some absurd number (kexp=10000).
Am I misunderstanding something or does CREST not support xtb with a custom parameter file?
Thanks!

Edit: Explicitly setting the XTBPATH to the paramether file path did not help, also I am using the -nci mode !

**Comment by pprcht** [comment]
Parameter files do not get copied locally, so having one in the working directory won't work automatically. 
However, working with the XTBPATH variable should be possible, we are never telling xtb to not follow its parameter loading instructions.

**Comment by yk07212** [comment]
Giving the parameter file its own folder and setting the XTBPATH variable made it work !
- Thanks

**Comment by pprcht** [comment]
If you are using the 2.12 version, or a >3.0 version in combination with the `--legacy` option, then the parameter change will probably work as described above.

For the default of CREST >3.0, I'll need to check how `tblite` can handle different xtb parameters.

**Comment by pprcht** [comment]
@ismiek, for `tblite` this is not as straight-forward as for xtb. However, I think I made it work properly #303 

Parameter files must be in toml format. Examples are located at  [assets/tblite/](https://github.com/crest-lab/crest/tree/master/assets/tblite/)

The parameter file can be specified within the `[[calculation.level]]` block:
```
[[calculation.level]]
method='tblite'
tblite_param='gfn1.toml'
```
which formally replaces any other `tblite` method selection.

**Comment by ismiek** [comment]
Hi,
I am very thankful for your response. Unfortunately, the tblite method didn't work. I downloaded the gfn1-si.toml file and my input file looks like this:

#this is a crest input file
input='crest_input_copy.xyz'
runtype='imtd-gc'

#parallelization
threads=8

[calculation]
[[calculation.level]]
method='tblite'
tblite_param='gfn1-si.toml'

my command to start the conformation analysis was: crest konf_analys_nsi4.toml  > gfn1_si.out
The calculation did run, but it didn't use gfn1-si as I can tell them apart from their si-si-binding length. Maybe I did something wrong, that's why I have put all these things.

**Comment by pprcht** [comment]
Maybe a stupid question, but did you also update your CREST binary?
I can reproducibly  affect the optimization of a Si dimer by providing the gfn1-si.toml file
