### ISSUE TITLE
TS conformer sampling converges on the product

### ISSUE THREAD

**Issue by Bitumelourd** [crest-lab/crest#228]
Hello

I am having problems running CREST 3.0 to sample constraint conformers from a Gaussian TS calculation in B3LYP-D3/6-31G(d,p) with THF as solvent. The conformer calculation converges slowly to the product. My constraints file looks like this

```
$constrain 
  atoms: 9, 5, 22 
  force constant= 2 
  reference=struc.xyz 
  distance: 9, 5, auto 
  distance: 5, 22, auto 
$metadyn
  atoms: 1-4, 6-8, 10-21, 23-48 
$end
```

where 9 - 5 is the bond being formed and 5 - 22 the bond being broken.

So far I've tried different force constants (0.5 and 1), constraining only atoms or distance with different force constants (0.5, 1 and 2), adding solvent using alpb and fixing selected atoms. In all cases, the conformers converge on the product.

I've read the documentation on fixation, constraint and confinement at https://xtb-docs.readthedocs.io/en/latest/xcontrol.html#detailed-input and I'm running out of ideas on what could go wrong.

I run CREST using :

`crest struc.xyz --chrg 1 -cinp constraints.inp --subrmsd > CrestAnalysis.txt`

Should I optimize the TS with a larger base set like 6-311++G(d,p)?

I've attached the initial TS, the structure supplied to CREST, the best conformers after 29 days of calculations and the CrestAnalysis.

[CREST.zip](https://github.com/crest-lab/crest/files/12747404/CREST.zip)

**Comment by pprcht** [comment]
There are two issues:
One, don´t use the `auto` setting while constraining bonds in CREST. This doesn't work and will cause degradation of the constraint over time. You might be seeing that in the enormous amount of restarts in the calculation you attached.
Two, the xtb-style constraints input might not be interfaced  correctly to the new calculators in the 3.0dev version. I've only recently touched that and some things are not uploaded.
Also, 29 days seems an awful lot, even considering the restarts. Are you running the program in parallel, I don't see the -T flag?

**Comment by Bitumelourd** [comment]
Thanks for the clarification!

I tried setting the distances in Angtrom. It works and only takes 22h. When should I use auto? Like in your example in CrestDocs when it is necessary to preserve non-covalent bonds that do not contribute to the TS vibration mode?

No, I don't run the program in parallel. For what I've tried, if I don't set the -T flag, I have for a similar calculation an estimated execution time for a batch of 14 MTD on 1 thread: 213 h 27 min 59 sec if I set -T 4 or 16 this estimated execution time increases to over 800 h.

**Comment by pprcht** [comment]
Well, you can safely use `auto` if you are only using `xtb` and use it for geometry optimizations, MDs, and  so on, starting from a single defined structure. Since CREST writes `xtb` inputs from all the metadynamics snapshots the `auto` value will default to whatever it is in these structures, instead of the reference value from the original input.
Hence, the short answer when to use `auto` for constraints in CREST is: never. If it somehow sounds different in the Docs I will have to fix or clarify that.

You should really run the program in parallel. In my opinion there is *never* a run where it will *not* improve the performance. The time estimate sounds wrong, maybe it was still a bit bugged in the 3.0dev binary you are using. I had to modify this (somewhat) recently

**Comment by Bitumelourd** [comment]
Ok, thanks for clarifying these points!

The calculation now takes less than a day in most cases, which is fine by me.
