### ISSUE TITLE
Not capturing enough higher energy rotamers

### ISSUE THREAD

**Issue by cassguff** [crest-lab/crest#237]
Hello,
I am working with diethyl carbonate, trying to capture all of the conformers and rotamers. I'm playing with the CREST settings to try to capture them all. The algorithm identifies all of the unique conformers that are given in literature, which is great, but for what I am doing I need an accurate count of all the rotamers as well. Literature would group the rotamers/conformers in two groups: a low energy group within 0.05kcal of the lowest energy conformer, and a higher-energy group between 2-2.5kcal away from the lowest energy conformer. There should be about 2x as many conformer/rotamers in this second group as the first group. But the algorithm is giving me twice as many in the first group as the second group. I've been playing with the settings to try to see if I can fix this but I haven't gotten it to work yet. Do you have any ideas on what I could do to try to help the algorithm sample more evenly for cases like this?

**Comment by pprcht** [comment]
Have you tried the entropy mode version (`-entropy` or `-v4`)? It is more thorough than the standard implementations.
However, it might be hard to get all rotamers of high-energy structures (in general), since the search itself is something like a Markov chain,  meaning you will get primarily low energy regions of the PES.

**Comment by cassguff** [comment]
I just tried that and it improved it a lot. Thanks for the tip!
