### ISSUE TITLE
Feature Request: export mapping file for the Molecular prototropy screening

### ISSUE THREAD

**Issue by xiki-tempula** [crest-lab/crest#24]
It might be desirable to know not only what is possible protomer, deprotomer, and tautomer but also their relationship to the original input molecule, given that topology checking is already in place.
I purpose that for each output molecule a mapping file could be created. Possible format could be

 ```
 15
 Element    input_index              output_index
 O               1              14
 O               2              13
 N               3             12
 C               4              11
 C               5              10
 C               6              9
 C               7              8
 C               8              7
 C               9              6
 C               10             5
 C               11              4
 H               -                3
 H               12              2
 H               13              1
 H               14              -
```
where the atom index 3 hydrogen in the output is not present in the input molecule and the atom index 15 hydrogen in the input file is not present in the output molecule.

**Comment by pprcht** [comment]
For the *initial* sorting this is now implemented and will be printed out in the beginning (*if* there is a change in the atom sorting, that is), but not for each individual protonated or deprotonated structure. 
For protonated structures in CREST this is trivial because the new proton is always appended to the list of atoms, but for deprotonated structures the order of H atoms might change again and needs to be mapped across the energetic sorting. The list of heavy atoms is unchanged and mapped correctly for all deprotomers, however.
I will try to update this functionality, but for now at least the initial mapping should help.

**Comment by xiki-tempula** [comment]
@pprcht Thank you for the explanation. My major problem at this stage is the tautomer, where the hydrogens are kind of shuffled during the course.
