### ISSUE TITLE
Not everybody is doing static linking!

### ISSUE THREAD

**Issue by pierre-24** [crest-lab/crest#256]
You people at Bonn like to assume that one prefer static linking (see, *e.g.*, [there](https://github.com/grimme-lab/xtb/pull/40)) ;)

However, while it is nice to have ready-to-use and -to-share executable, don't forget that you create codes that can be used on supercomputer, where static linking is generally the exception, not the rule (thanks to the `module` systems and so forth). So, would it be possible to remove [line 25-27 of `meson.build`](https://github.com/crest-lab/crest/blob/master/meson.build#L25-L27) and/or add a specific option to do so (it was `-Dstatic=false` in xtb, but they seems to do it differently now)? Thanks in advance :)

**Comment by pprcht** [comment]
I won't remove the option by default (for now) because this build is used for the precompiled binary.

If you need a build specific for your HPC system you can either edit the meson build yourself or try the CMake version, which should be dynamically linked by default.

I'll try to create dedicated build option though, that might be useful.

**Comment by pierre-24** [comment]
I was indeed able to compile the project by commenting the lines I mentioned, using gfortran. However, it does not works with mkl, for which you gave to transmit the options to other projects (tblite, for example). So having a dedicated option is definitely the way to go :)
