### ISSUE TITLE
 WARNING! Change in topology detected!

### ISSUE THREAD

**Issue by Yuandq** [crest-lab/crest#28]
Recently, I read a nice paper named "Efficient Calculation of Small Molecule Binding in Metal−Organic Frameworks and Porous Organic Cages" from JPCC. I want to repeat the result of CO2@MOF-5 . When I did it, I got a warning " WARNING! Change in topology detected!". I want to know that it is reasonable?
Here is my command line:
 crest struc.xyz -cinp .xcontrol -nci -gff --noreftopo
.xcontrol:
$metadyn
  atoms: 401-403
$end

Thanks in advance.

**Comment by pprcht** [comment]
This warning exists only because some systems change their geometry already upon optimization in `xtb`, so that there are no bad surprises. Often it still is fine and the warning can be seen as a formality. If you get this warning you can check the optimization trajectory (`xtbopt.log`) and decide yourself if the final structure is ok. If so, then the `--noreftopo` option should be fine and I see no problem with your command line call.

**Comment by Yuandq** [comment]
Thanks for your quick reply. In the JPCC paper, the authors said "Because possible binding sites of the guest molecule inside the host are in the focus, the biasing root-mean-square deviation (RMSD) potential in the MTD is only applied to the guest molecule
throughout. The host is free of any constraints, allowing structural relaxation and adaption to the guest."
Is my .xcontrol file OK to achieve the above constrains about the guest RMSD？
Thanks！

**Comment by sespic** [comment]
Yes, your input is correct. Assuming that CO2 are atoms 401, 402, and 403 you will only consider those three atoms in the  meta-dynamic simulation.
