### ISSUE TITLE
Output gets deleted

### ISSUE THREAD

**Issue by jessman** [crest-lab/crest#280]
At the end of a CREST calculation with version 3.0pre, the verbose output (list of optimizations, list of MTDs, number of structures, etc.) gets automatically deleted from the SLURM output file and replaced with a short summary of the time that each process took in percentages. Is there a way to keep the verbose output, as was the case in 2.x versions? Thanks!

**Comment by pprcht** [comment]
Interesting, if true, that is not on purpose. The runtime summary is new and should not replace the other output. Do you have an example saved that I could look at?

**Comment by jessman** [comment]
Hi, attached is the slurm output file. Thx!
[slurm-27835936.txt](https://github.com/crest-lab/crest/files/14789642/slurm-27835936.txt)

**Comment by pprcht** [comment]
I could partially reproduce this on our own slurm cluster. 

**The bad news**: 
This seems to be an artifact of using `--scratch`, and I have currently no idea what exactly is causing it or how to fix it in the code.

**The good news**: 
For the standard runtypes of CREST 3 you won't need the `--scratch` workaround anymore. Since we have moved from a `xtb`-subprocess based version to the `tblite` calculator, the problematic amount of I/O is gone. You also won't be needing the `--xnam` in this case.

Also, I think it would make sense for you to pipe the output in some separate file explicitly (`> output` or something), rather than relying on the slurm pipe.
