### ISSUE TITLE
Updating conda to the latest version

### ISSUE THREAD

**Issue by moabe84** [crest-lab/crest#295]
Hi Philipp,
Is it possible to update conda to the latest version? Currently, it's running version 2.12. Thanks.

Mostafa

**Comment by corinwagen** [comment]
Agreed! lmk if I can help.

**Comment by pprcht** [comment]
[![Conda Version](https://img.shields.io/conda/vn/conda-forge/crest?color=khaki)](https://anaconda.org/conda-forge/crest)

```
conda install conda-forge::crest
```

It's online, download on a fresh conda env and running a few test examples works for me. May require setting `export OPENBLAS_NUM_THREADS=1` if you are using OpenBLAS as the LA backend, otherwise there is an ugly warning in the concurrent part. I added this info to the README.md

I'm marking the issue as complete.
