### ISSUE TITLE
V2.11 entropy mode from previous ensembles?

### ISSUE THREAD

**Issue by ghutchis** [crest-lab/crest#30]
First off, congrats - 2.11 looks great! I'm very happy that `zsort` is no longer the default.

I have a large number of previous ensembles. 😄 
(https://chemrxiv.org/articles/preprint/Understanding_Conformational_Entropy_in_Small_Molecules/12671027)

I'd like to calculate the new absolute entropies with v2.11. Can I use `-forall` on an old ensemble?

The preprint seems to suggest that one needs to start with a previous best minima and run a new ensemble?

I guess my question is for Sconf entropy purposes, how different are the CREST 2.10 and 2.11 entropy values? Do I need to re-start my ensembles for more accurate Sconf? (If you don't know, send me an e-mail. I can restart ~10,000 ensembles to compare.)

**Comment by pprcht** [comment]
Thanks! Yes, `zsort` in the end did cause more inconvinience than it did help with the conformer generation.

The different components of the conformational entropy from the preprint can be calculated seperately, however, one thing that will be missing is the extrapolation to ensemble completness, as this requires the intermediate ensembles.

For a given ensemble the Gibbs-Shannon entropy (S'_conf without the extrapolation in the preprint) is roughly the same as the entropy in 2.10. In fact, we still use the 2.10 type calculation for the entropy estimate during the iterations to apply thresholds.
The new formulation mainly differs from 2.10 by inclusion of the degeneracy factor g'_i. To calculate this with g'_i use the two commands:
1.  `crest --cregen crest_rotamers.xyz --entropy`
2.  followed by `crest --for crest_rotamers.xyz --entropy`
It is important to use the `crest_rotamers.xyz` file here because we try to identify all necessary degeneracy information from the present structures.

The other contribution that is completely new compared to the previous version is the RRHO population average (\overline{S}_msRRHO in the ChemRxiv preprint, or δSrrho in the program printout). This can be calculated with `crest --rrhoav crest_conformers.xyz`. Use the `crest_conformers.xyz` or the `crest_ensemble.xyz` from step 1 above.

For small molecules the entropy difference in comparison to the older CREST versions is not very large and also the extrapolation will be insigificant, but for drug-like molecules it is another story. Starting from already found global minima is mostly relevant to save some iterations in the new workflow. The entropy workflow will also restart when a better global minimum is found, but the iterations are much more costly than with the default runtype. Sadly the computation of the conformational entropy is an expensive convergence problem. Hence also the recommendation to use the faster GFN-FF instead of GFN2. 

Hopefully this will be useful for you, I will try to detail the usage of `--entropy` with some examples in the documentation sometimes within the following days.

**Comment by ghutchis** [comment]
Yes, I realize I'm "jumping the gun" - before the documentation is updated for xtb 6.4 / crest 2.11.

Yeah, makes sense - unfortunately we haven't been keeping the `crest_rotamers.xyz` files, so we'll have to do some work there (although switching to GFN-FF / GFN2 mixed should save a lot of time).

We've sent off ~3000 molecules to see how big the differences are.

I agree the conformer entropy is an expensive problem - which is one reason we developed approximate descriptors. (Also, I wanted to understand the trends in alkane / rotatable bonds.)

Hope the manuscript is treated well, it's great work!
