### ISSUE TITLE
Defaults equivalence: v. 2.12 and v.3.01

### ISSUE THREAD

**Issue by aslozada** [crest-lab/crest#304]
Hi,

I carried out a test to compare the results of Conformational Sampling between versions 2.12 and 3.01 of CREST. In this test, the calculation is performed sequentially on models of linear alkanes, CnH2n+2 (n=2,10). 
As can be seen in the figure below, the number of conformers  in version 2.12 is always greater than the quantities obtained with version 3.0.1. On the other hand, the energy values in both cases are in the range of (0.0, 6.0) kcal/mol (as shown in the file crest.energies). The execution of CREST, in both cases, was in standard command-line mode: crest file.xyz --gfn2 -T 8 (v.2.12), and crest file.xyz --gfn2 -T 8 (v.3.0.1).

![g1](https://github.com/crest-lab/crest/assets/3170541/19fc8115-c046-4c2f-9c52-d43be0638a4b)

I would be very grateful for any information.

Are the default values the same in both versions (parameters such as Vbias, ewin, etc.)?

**Comment by pprcht** [comment]
Hi,
The defaults are the same in both versions, the difference is only the backend implementation of the xTB Hamiltonians. 
In the 3.0+ versions we got rid of the I/O communication layer between xtb and CREST and instead are using the `tblite` implementation. Both implementations of the Hamiltonian are consistent except for the implicit solvation, although very minor differences may occur due to the different code structure.
However, I believe the newer versions to be a bit "cleaner", i.e. part of what you are seeing here is likely from false positive cases.
