### ISSUE TITLE
Topology change error yet log message indicates successful geometry optimization

### ISSUE THREAD

**Issue by tfhughes** [crest-lab/crest#344]
Please see the attached tarball containing Crest input and output for an example that fails with the topology change error. We run Crest jobs on many organometallic complexes and frequently see this issue. I want to understand what actually needs to be done to fix it. Maybe https://github.com/crest-lab/crest/issues/244 is supposed to help?

Also in such a case the log message 'A)' at the end of the output indicates that preoptimization could fix the issue yet a few lines above the following message seems to indicate that a preoptimization was already performed prior to the dynamics:

`
-----------------------------
 Initial Geometry Optimization
 -----------------------------
 Geometry successfully optimized.
`

So I am confused why 'A)' is a recommendation if it was already done.

Also I am confused about whether that preoptimization was actually done. If I compare my input 2Zn.xyz, output crest_input_copy.xyz, and the first structure in output crestopt.log (all in the attached tarball) and superimpose them in some kind of viewer you can see that they are identical. As I understand it crestopt.log is the dynamics and so the expectation given the log message is that the input to the dynamics would have been optimized and therefore different from the input structure.

[github.tar.gz](https://github.com/user-attachments/files/17044413/github.tar.gz)

**Comment by pprcht** [comment]
A) is recommended because the whole printout is predefined and doesn't know about what the program did up to this point and what not. There are runtypes without the automatic preoptimization and one can turn it off.

However, I think in your case the recommendation is correct. `crestopt.log` is **NOT** the dynamics, it is the optimization trajectory. I.e. it shows what happened during the optimization (the very same that is declared as "successful" in the printout), so what you need to compare to understand the topology failure are the first and last structure in `crestopt.log`, the first being your original input, the last being the optimization outcome. As the printout tells you there is a topology change between one Zn and one O, looking at the optimization trajectory a molecule viewer will depict a bond there:
Start:
![image](https://github.com/user-attachments/assets/7e3579aa-f680-4e8f-896c-2be6f2b4650b)

End:
![image](https://github.com/user-attachments/assets/4427ab6e-e267-42b3-88a2-7ee7ce51d3af)


So if you *actually* want to follow the recommendation of A), start the procedure from the last structure in `crestopt.log`. This is not done automatically (except if you use the `-notopo` flags of the other two recommendations) because it is a user responsibility to judge if the optimized structure is still sensible.

**Comment by tfhughes** [comment]
Makes sense and thank you for the explanation.

As I understand it --noreftopo applies during the optimization, which is prior to the conformational search, and --notopo (with optional atom list) applies during the conformational search. As you indicate in the last message the optimization changes the topology and we can ignore that by using --noreftopo. Suppose then that during the following conformational search the topology changes again (including the possibility of back to what it originally was prior to optimization). I don't think I have seen that case yet so I can't test it but we would control it with --notopo?

Since we are interested in high throughput, Crest IO is in xyz, and bonds and bond orders depend on algorithm does it make sense to always run Crest using --noreftopo and --notopo and then check for things like bonding, chirality changes, etc. relative to the input on our end?

**Comment by pprcht** [comment]
For  metallorganic chemistry it is not unreasonable to have these flags present, and usually using both commands simultaneously is what's working best. 
There is unfortunately a limit to sensible automated (topology) checks, as they can't fully replace chemical intuition. So, yes, it makes sense to check at the end.

**Comment by tfhughes** [comment]
Thank you. Feel free to resolve this case.
