### ISSUE TITLE
gfn2//gfnff composite mode & negative conformation entropy

### ISSUE THREAD

**Issue by jungsdao** [crest-lab/crest#72]
Hello, and thank you for developing such an outstanding tool!
I have three questions:
1. I'm dealing with some linear  open shell molecule. As far as I know, GFNFF is not robust on open shell compound. I found `-gfn2//gfnff` composite mode in CREST and wondered this might be help reducing computational time and enhance accuracy issue simultaneously. 
Does `-gfn2//gfnff` means that geometry optimization is done under gfnff level and only energy evaluation is done under gfn2-xtb level? 
How reliable this method would be ?

2. In this paper, authors tested S_conf for LBH & AS23 test set and outliers have been removed from statistics. 
Authors selected value from GFN2-xTB rather than GFNFF, presumably they trust accuracy gfn2-xtb over gfnff. 
If, for a certain system, there are quite large difference between GFN2-xtb and GFNFF, should the value from GFN2-xTB should be used?
For example, if there're open shell compound would GFN2-xTB value should be preferred over GFNFF?

3. I got negative conformational entropy from one of my result.
`------------------------------------------`
` | FINAL MOLECULAR ENTROPY AT T= 298.15 K |`
` ------------------------------------------`
`   Sconf   =          8.345611`
` + δSrrho  =         -9.142591`
` ----------------------------------------`
` = S(total)  =         -0.796980`

Is there any physical meaning for negative conformation entropy or is it just wrong result?
It seems averaging over S_RRHO of confomer ensemble caused this problem, but I have no clue why this occurred.

**Comment by pprcht** [comment]
Hi,
To answer your questions in order:
1. Yes, `--gfn2//gfnff` does the MD/MTD and optimization at GFN-FF level, and the energy evaluation+the ensemble sorting at GFN2-xTB level. The energetics hence will be a bit better than at the force-field level, but the geometries might be biased by the characteristics of GFN-FF. All in all, the acurracy is probably in between GFN2 and GFN-FF.
2. Yes, our conclusion was that GFN2-xTB tends to get the better results. But keep in mind that GFN-FF will be sigificantly faster in this mode. Still, differences in the results are often small, so you have to decide if this is worth the effort. If you feel that GFN-FF isn't sufficient for your open-shell system, go for GFN2.
3. This can (rarely) happen due to the δS_RRHO value, since this is an average over the ensemble shifted by the S_RRHO value of the lowest conformer. It means that the lowest conformer has a (much) larger S_RRHO contribution than the rest of the ensemble on average. The actual Gibbs-Shannon contribution in your output looks healthy with 8.35 cal/molK, but is compensated by the δS_RRHO part.
